In [6]:
import pandas as pd

In [7]:
df = pd.read_csv(r'C:\Users\Valmik Belgaonkar\OneDrive\Desktop\SIH-GLOF\sihGlof\resources\glacier_inventory_region_extract.csv', usecols=[' lat', ' lon', ' total_area', ' mean_width', ' mean_depth', ' mean_length', ' max_elev', ' min_elev', ' mean_elev'])

In [8]:
print(df.columns)

Index([' lat', ' lon', ' total_area', ' mean_width', ' mean_length',
       ' mean_depth', ' mean_elev', ' max_elev', ' min_elev'],
      dtype='object')

In [9]:
df.to_csv('attributes.csv')

In [10]:
df

,lat,lon,total_area,mean_width,mean_length,mean_depth,mean_elev,max_elev,min_elev
0,34.672,68.874,1.2800,,,,4110,4250,3975
1,34.676,68.855,0.3100,,,,4350,4450,4250
2,34.689,68.854,0.6000,,,,4100,4200,4000
3,34.707,68.857,0.5600,,,,4175,4350,4000
4,34.719,68.852,1.0600,,,,4050,4350,3750
...,...,...,...,...,...,...,...,...,...
28819,34.656,75.116,0.0520,,0.2400,10.3400,,,
28820,34.641,75.201,0.0290,,0.3100,7.2600,,,
28821,34.629,75.192,0.1690,,0.4300,19.9500,,,
28822,34.624,75.177,0.2310,,0.8400,22.9200,,,
28823,34.620,75.174,0.1680,,0.4400,19.9500,,,